1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans. NumPy (Numerical Python) is a fundamental library for scientific computing in Python, providing powerful capabilities for numerical operations and data analysis. Here’s an overview of its purpose, advantages, and how it enhances Python’s capabilities:

Purpose of NumPy
Numerical Computing: NumPy is designed for efficient numerical computing. It provides support for large, multi-dimensional arrays and matrices, as well as a wide range of mathematical functions to operate on these arrays.

Data Analysis: NumPy is a key component in the data analysis ecosystem. It forms the basis for other scientific computing libraries in Python, such as SciPy, pandas, and scikit-learn.

Advantages of NumPy
Performance:

Efficient Array Operations: NumPy arrays (ndarray) are implemented in C, which makes them significantly faster than Python's built-in lists for numerical operations. Operations on NumPy arrays are performed in compiled code, which is highly optimized for performance.
Vectorization: NumPy supports vectorized operations, allowing you to apply operations to entire arrays without explicit loops. This leads to more concise and efficient code.
Multidimensional Arrays:

Array Object (ndarray): NumPy provides the ndarray object, which supports multi-dimensional arrays. This is crucial for scientific computing tasks that require handling of matrices, tensors, and higher-dimensional data.
Shape and Broadcasting: NumPy arrays support broadcasting, which allows for operations between arrays of different shapes in a flexible and efficient manner.
Mathematical Functions:

Comprehensive Library: NumPy includes a wide range of mathematical functions, including linear algebra, statistical, and Fourier transform operations. This makes it a versatile tool for a variety of numerical tasks.
Integration with C/C++: NumPy provides tools to interface with C and C++ code, enabling integration with high-performance computing libraries.
Ease of Use:

Concise Syntax: NumPy’s syntax for array operations is concise and expressive. It simplifies complex numerical computations and data manipulations with minimal code.
Rich Functionality: Functions for mathematical operations, random number generation, and array manipulation make NumPy a comprehensive library for scientific computing.
Interoperability:

Integration with Other Libraries: NumPy serves as the foundational library for other scientific computing libraries like SciPy (for advanced scientific computations), pandas (for data analysis and manipulation), and scikit-learn (for machine learning). This integration allows for a seamless workflow between different tools and libraries.
Community and Documentation:

Active Community: NumPy has a large and active community that contributes to its development, ensuring continuous improvement and support.
Extensive Documentation: Comprehensive documentation and numerous tutorials make it easier for users to learn and effectively utilize NumPy.
How NumPy Enhances Python’s Capabilities
Speed and Efficiency: NumPy’s array operations are implemented in C, providing performance improvements over Python’s built-in data structures. This is particularly important for large-scale data computations.

Support for Large Data Sets: NumPy’s array structures can handle large data sets efficiently, which is essential for scientific and data analysis tasks that involve big data.

Advanced Mathematical Operations: NumPy provides built-in support for a wide range of mathematical operations, which would otherwise require complex implementations in pure Python.

Foundation for Scientific Computing: NumPy forms the backbone for many other scientific computing libraries. Its array handling capabilities and mathematical functions make it an indispensable tool in the scientific Python ecosystem.

In summary, NumPy is crucial for scientific computing and data analysis in Python due to its performance, functionality, and integration with other libraries. It enhances Python’s capabilities by providing efficient numerical operations, multi-dimensional array handling, and a rich set of mathematical functions.


2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans. Both np.mean() and np.average() functions in NumPy are used to calculate the average of elements in an array, but they have some key differences in their capabilities and usage. Here’s a comparison of the two functions:

Summary of Differences
Functionality:

np.mean(): Computes the arithmetic mean of the elements in an array.
np.average(): Computes the weighted average if weights are provided, otherwise it computes the arithmetic mean.
Weights:

np.mean(): Does not support weights.
np.average(): Supports weights, allowing for a weighted average calculation.
Additional Outputs:

np.mean(): Returns only the mean.
np.average(): Can return both the average and the sum of weights (if returned=True).
When to Use Which
np.mean(): Use this when you need a straightforward average calculation without considering weights. It’s more concise and sufficient for many typical averaging tasks.
np.average(): Use this when you need to calculate a weighted average or when you require the additional information about the weights. It provides more flexibility in terms of averaging with different significance for each element.
Both functions are useful tools for different scenarios in data analysis and numerical computations.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans. Reversing a 1D Array:

[::-1]: This slice notation means to take the array elements in reverse order.


Reversing a 2D Array:

Reversing along the first axis (rows): Use [::-1, :] to reverse the rows of the array. The colon : indicates that all columns should be included.
Reversing along the second axis (columns): Use [:, ::-1] to reverse the columns of the array. The colon : indicates that all rows should be included.
Reversing along both axes: Use [::-1, ::-1] to reverse the array along both dimensions. This reverses the order of both rows and columns.
Additional Notes
The slicing method ([::-1]) works for arrays of any dimensionality, but you need to specify the appropriate axis for multidimensional arrays.
Reversing along axes is commonly used in various applications such as data manipulation, image processing, and analysis.

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans. Determining the data type of elements in a NumPy array is essential for understanding how data is stored and processed. NumPy provides several methods for checking and managing data types, which significantly impact memory management and performance.

Determining the Data Type of Elements
You can determine the data type of elements in a NumPy array using the 'dtype' attribute.

Importance of Data Types
Memory Management:

Efficient Storage: Different data types use different amounts of memory. For example, int32 uses 4 bytes per element, while int64 uses 8 bytes. Choosing the appropriate data type can significantly reduce memory usage, especially for large arrays.
Precision vs. Memory: For floating-point numbers, float32 and float64 represent 32-bit and 64-bit precision, respectively. Higher precision requires more memory. Depending on the application, you may choose float32 for less precision and lower memory usage or float64 for more precision.
Performance:

Computational Efficiency: Operations on arrays with smaller data types (e.g., int8 vs. int64) can be faster because less data needs to be processed. However, some operations may be optimized for specific data types, so the choice of data type can impact performance.
Hardware Optimization: Modern processors are optimized for certain data types. For example, many processors handle 32-bit integers more efficiently than 64-bit integers. Using the appropriate data type can leverage these hardware optimizations.
Compatibility:

Interoperability: Data types affect how data is shared between different libraries and systems. Ensuring compatibility between data types when interfacing with other libraries or systems is crucial for accurate and efficient data processing.
Consistency: Maintaining consistent data types across arrays helps avoid issues related to data conversion and ensures consistent behavior in calculations.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans. In NumPy, ndarray (short for n-dimensional array) is the central data structure for numerical computations. It provides a powerful and efficient way to store and manipulate large datasets. Here’s a detailed overview of ndarray, its key features, and how it differs from standard Python lists:

Definition of ndarray
ndarray is a multidimensional array object that can hold elements of the same data type. It supports a variety of operations, including mathematical computations, logical operations, and data manipulation.

Key Features of ndarray
Homogeneous Data:

Uniform Type: All elements in an ndarray are of the same data type, which allows for efficient storage and operations. This contrasts with Python lists, which can contain elements of different types.
Multidimensional:

Axes and Dimensions: ndarray supports multiple dimensions (axes). You can create 1D, 2D, 3D, or even higher-dimensional arrays. For example, a 2D array can be seen as a matrix, and a 3D array can be visualized as a stack of matrices.
Shape: The shape of an ndarray is represented as a tuple of integers, specifying the size along each dimension (e.g., (3, 4) for a 2D array with 3 rows and 4 columns).
Efficient Operations:

Vectorization: ndarray supports vectorized operations, allowing element-wise operations without explicit loops. This leads to more concise and faster code.
Broadcasting: Enables operations between arrays of different shapes by automatically expanding the dimensions of smaller arrays to match larger ones.
Mathematical and Statistical Functions:

Built-in Functions: NumPy provides a wide range of mathematical and statistical functions that can be applied to ndarray, including mean, median, standard deviation, and more.
Memory Efficiency:

Compact Storage: ndarray uses contiguous memory allocation for storing elements, which reduces overhead and improves performance compared to Python lists.
Indexing and Slicing:

Advanced Indexing: Supports slicing, boolean indexing, and advanced indexing, providing powerful tools for accessing and modifying array elements.
Data Type Specification:

dtype: Each ndarray has an associated dtype (data type) that specifies the type of elements it holds, such as int32, float64, etc. This enables efficient storage and operations tailored to specific types.
Differences from Standard Python Lists
Data Type:

ndarray: Elements are of the same data type, allowing for optimized operations and memory usage.
Python Lists: Can contain elements of different data types, leading to potential inefficiencies in operations and memory usage.
Performance:

ndarray: Optimized for numerical operations and large-scale data processing. Operations are implemented in C and are typically faster.
Python Lists: Slower for numerical operations due to their flexibility in handling different data types and lack of specialized optimizations.
Multidimensional Support:

ndarray: Supports multidimensional arrays (e.g., 2D matrices, 3D tensors) with operations defined across axes.
Python Lists: Standard lists are 1D, but you can create nested lists to mimic multidimensional arrays, which is less efficient and lacks native support for multidimensional operations.
Operations:

ndarray: Supports vectorized operations, broadcasting, and mathematical functions directly.
Python Lists: Operations on lists require explicit loops or list comprehensions, and mathematical functions must be applied element-wise manually.
Memory Layout:

ndarray: Uses contiguous memory allocation, which is more efficient for numerical operations.
Python Lists: Elements are stored as references in a dynamically allocated structure, leading to more overhead.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans. ndarray: Optimized for numerical operations and large-scale data processing. Operations are implemented in C and are typically faster.
Python Lists: Slower for numerical operations due to their flexibility in handling different data types and lack of specialized optimizations.
Multidimensional Support:

ndarray: Supports multidimensional arrays (e.g., 2D matrices, 3D tensors) with operations defined across axes.
Python Lists: Standard lists are 1D, but you can create nested lists to mimic multidimensional arrays, which is less efficient and lacks native support for multidimensional operations.
Operations:

ndarray: Supports vectorized operations, broadcasting, and mathematical functions directly.
Python Lists: Operations on lists require explicit loops or list comprehensions, and mathematical functions must be applied element-wise manually.
Memory Layout:

ndarray: Uses contiguous memory allocation, which is more efficient for numerical operations.
Python Lists: Elements are stored as references in a dynamically allocated structure, leading to more overhead.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans. In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. They allow you to combine arrays along different axes. Here’s a comparison of these functions, including examples and their outputs:

numpy.vstack()
Purpose: Stacks arrays vertically (row-wise). This function concatenates arrays along the first axis (axis=0), resulting in a new array with the arrays placed on top of each other.

numpy.hstack()
Purpose: Stacks arrays horizontally (column-wise). This function concatenates arrays along the second axis (axis=1), resulting in a new array with the arrays placed side by side.

In [ ]:
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Stack arrays vertically
result_vstack = np.vstack((arr1, arr2))

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Result of vstack:\n", result_vstack)
'''Array 1:
 [[1 2 3]
  [4 5 6]]
Array 2:
 [[ 7  8  9]
  [10 11 12]]
Result of vstack:
 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]'''

# Stack arrays horizontally
result_vstack = np.hstack((arr1, arr2))

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Result of vstack:\n", result_vstack)

'''Array 1:
 [[1 2 3]
  [4 5 6]]
Array 2:
 [[ 7  8  9]
  [10 11 12]]
Result of hstack:
 [[ 1  2  3  7  8  9]
  [ 4  5  6 10 11 12]]'''

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans.In NumPy, fliplr() and flipud() are methods used to reverse the order of elements in an array along specific axes. These functions are useful for various data manipulations and visualizations. Here’s a detailed comparison of their effects and how they operate on different array dimensions:

numpy.fliplr()
Purpose: Flips an array left-to-right along the second axis (columns) for 2D arrays.
Parameters:

m: Input array, which should be at least 2-dimensional.
Effect:

For 2D arrays, fliplr() reverses the order of elements in each row, effectively flipping the array horizontally.
For 1D arrays or arrays with more than 2 dimensions, fliplr() operates on the last two dimensions (i.e., it treats the last two dimensions as 2D arrays and flips them left-to-right).

numpy.flipud()
Purpose: Flips an array up-to-down along the first axis (rows) for 2D arrays.

Parameters:

m: Input array, which should be at least 2-dimensional.
Effect:

For 2D arrays, flipud() reverses the order of rows, effectively flipping the array vertically.
For 1D arrays or arrays with more than 2 dimensions, flipud() operates on the first two dimensions (i.e., it treats the first two dimensions as 2D arrays and flips them up-to-down).

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans. The array_split() method in NumPy is a versatile function used to split an array into multiple sub-arrays. It allows for flexible splitting, even when the array cannot be evenly divided. Here’s a detailed discussion of its functionality and how it handles uneven splits:

numpy.array_split()
Purpose: Splits an array into multiple sub-arrays along a specified axis. The function can handle cases where the array does not split evenly, distributing elements as evenly as possible.

Parameters:

ary: The input array to be split.
indices_or_sections: Defines how to split the array. It can be:
An integer: Number of equal sections to split the array into.
A 1D array of indices: Specifies where to split the array.
axis: Axis along which to split the array (default is 0).
Return Value:

A list of sub-arrays, where each sub-array is a portion of the original array. The number of sub-arrays depends on the value of indices_or_sections and how the elements are distributed.

Handling Uneven Splits
When splitting an array into sections that are not evenly divisible, array_split() handles the uneven distribution by allocating elements as evenly as possible among the sub-arrays. The function ensures that the number of elements in each sub-array differs by at most one.

Summary
Functionality: array_split() splits an array into multiple sub-arrays along a specified axis, handling cases where the array cannot be evenly divided.
Uneven Splits: When the array cannot be evenly split, array_split() distributes elements as evenly as possible, ensuring that each sub-array differs by at most one element.
Flexibility: The method can split arrays into equal sections or at specific indices, and it supports splitting along any axis for multidimensional arrays.
Understanding how to use array_split() allows for flexible data manipulation and can be particularly useful for dividing datasets into manageable chunks or for data processing tasks.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans. Vectorization and broadcasting are two key concepts in NumPy that significantly enhance the efficiency of array operations and numerical computations. Here’s a detailed explanation of each concept and how they contribute to efficient array operations:

Vectorization
Concept: Vectorization refers to the process of applying operations to entire arrays (or large chunks of data) at once, rather than using explicit loops. This approach leverages optimized low-level implementations and parallel processing to perform operations efficiently.

Key Points:

Element-Wise Operations: With vectorization, operations are applied element-wise to arrays. For example, adding two arrays together will perform the addition operation on each corresponding pair of elements without the need for an explicit loop.

Efficiency: Vectorized operations are typically implemented in C and use highly optimized routines, making them faster than equivalent operations written using Python loops. They also take advantage of modern CPU architectures and vectorized instructions.

Simplicity: Vectorization allows for concise and readable code. Instead of writing complex loops, you can perform operations with simple array expressions.

Broadcasting
Concept: Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes and dimensions by automatically expanding the smaller array to match the shape of the larger array. This technique avoids the need for explicit replication of data and enables operations between arrays with different shapes.

Key Points:

Compatibility: Broadcasting enables operations between arrays that do not have the same dimensions. It works by aligning the shapes of the arrays in a way that they are compatible for element-wise operations.

Rules: The broadcasting rules are:

If arrays have different numbers of dimensions, the smaller-dimensional array is padded with ones on the left.
Dimensions of the arrays are compared element-wise from the trailing dimensions. Two dimensions are compatible if they are equal or one of them is 1.
Arrays are broadcast to the shape of the larger array.
Efficiency: Broadcasting avoids the overhead of creating large temporary arrays by performing operations directly on the input arrays with the appropriate shape. This reduces memory usage and improves performance.

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

arr=np.random.randint(1,100,(3,3))
new_arr=np.transpose(arr)
print(new_arr)

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np

arr=np.random.rand(10)
new_arr=np.reshape(arr,(2,5))
print(new_arr)
final_arr=np.reshape(new_arr,(5,2))
print(final_arr)

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
import numpy as np
arr=np.random.randn(4,4)
arr=np.pad(arr, pad_width=1, mode='constant',constant_values=0)
print(arr)


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np
arr=np.arange(10,61,5)
print(arr)

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
import numpy as np 
x=['python', 'numpy', 'pandas']
arr= np.array(x)
arr_t=np.char.title(arr)
print(arr_t)
arr_u=np.char.upper(arr)
print(arr_u)
arr_l=np.char.lower(arr)
print(arr_l)


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np
words=input('please enter you words by space seperated').strip().split(' ')
arr=np.array(words)
arr=np.char.join(' ',arr)
print(arr)

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np
arr1=np.random.randint(1,1000,(4,4))
arr2=np.random.randint(1,1000,(4,4))
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(np.divide(arr1,arr2))

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np

arr= np.identity(5,dtype=int)
arr1=np.diagonal(arr)
print(arr1)

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [ ]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate random array of integers
arr = np.random.randint(0, 1000, 100, dtype=int)

# Apply the prime number check element-wise
prim_arr = np.array([x for x in arr if is_prime(x)])

# Print the arrays
print("Original array:", arr)
print("Prime numbers array:", prim_arr)


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [ ]:
import numpy as np
arr=np.random.uniform(20,35,30)
print(arr)
j=0
window_size=7
for i in range(1,len(arr)//7 +2):
    temp=np.mean(arr[j:j+window_size])
    print(f"week{i} average temperature is {temp}")
    j+=7
